### ISSUE TITLE
Add more python basic programs

### ISSUE THREAD

**Issue by Anshullakhera** [Rishi098/Basic-Python-Programs#46]

**Comment by Rishi098** [comment]
Thank you for your contribution! 🙌
Before I merge your changes, it would be awesome if you could take a moment to give a ⭐️ to my repositories. Your support really helps me keep improving and maintaining the projects!

Once you've done that, I'll go ahead and merge your request.

Thanks again for your help! 😊

**Comment by Anshullakhera** [comment]
Of course!

**Comment by Anshullakhera** [comment]
You can check it now i have given a  ⭐️ to your repositories

**Comment by Rishi098** [comment]
Thank You
